application: gulimulife-hr
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
  
- url: /calendar.*
  script: gulimu_calendar.calendar_oauth.app
  login: required

- url: /everyday.*
  script: gulimu_everyday.everyday.app
  login: required

- url: /soc.*
  script: gulimu_soc.soc.app
  login: required

- url: /travelmap.*
  script: gulimu_travelmap.travelmap.app
  login: required
  
- url: /tenthousand.*
  script: gulimu_tenthousand.tenthousand.app
  login: required

- url: /index\.html
  script: gulimulife.app
  
- url: /
  script: gulimulife.app

- url: /(google7c2892bc8e0b7d79\.html)
  static_files: static/misc/\1
  upload: static/misc/(google7c2892bc8e0b7d79\.html)

- url: /.*
  script: not_found.app

libraries:
- name: django
  version: "1.2"
  

  

  
