application: gulimulife
version: 8
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
  
- url: /calendar.*
  script: gulimu_calendar/calendar_oauth.py
  login: required

- url: /everyday.*
  script: gulimu_everyday/everyday.py
  login: required

- url: /travelmap.*
  script: gulimu_travelmap/travelmap.py
  login: required
  
- url: /skillchart.*
  script: gulimu_skillchart/skillchart.py
  
- url: /tenthousand.*
  script: gulimu_tenthousand/tenthousand.py
  login: required

- url: /index\.html
  script: gulimulife.py
  
- url: /
  script: gulimulife.py

- url: /.*
  script: not_found.py
  

  

  
