application: gulimulife
version: 8
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
  
- url: /step1.*
  script: step1.py
  
- url: /step2.*
  script: step2.py
  
- url: /step3.*
  script: step3.py
  
- url: /user.*
  script: gulimulife.py
  login: required
  
- url: /calendar.*
  script: gulimu_calendar_oauth.py
  login: required
  
- url: /travelmap.*
  script: gulimu_travelmap.py
  login: required
  
- url: /test.*
  script: gulimu_playground.py
  login: required

- url: /index\.html
  script: gulimulife.py
  
- url: /
  script: gulimulife.py

- url: /.*
  script: not_found.py
  

  

  
